### ISSUE TITLE
Verification of elAddr and clAddr in Config are in the same network environment

### ISSUE THREAD

**Issue by duktig666** [NodeDAO/oracle-go#5]
Verification of elAddr and clAddr in Config are in the same network environment:
```yaml
eth:
  network: mainnet
  elAddr:
  clAddr:
```

If you are not in the same network environment, report an error and print the log.
